---
- name: "Check for kafka_exporter binary"
  ansible.builtin.stat:
    path: '{{ kafka_exporter_install_dir }}/kafka_exporter'
  changed_when: false
  register: kafka_exporter_install

- name: "Install tasks"
  when: not kafka_exporter_install.stat.exists or kafka_exporter_force_install|bool
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: ["ca-certificates", "unzip", "tar"]
        state: present

    - name: "Download kafka_exporter..."
      ansible.builtin.get_url:
        url: '{{ kafka_exporter_tgz_url }}'
        dest: '{{ kafka_exporter_temp_dir }}/{{ kafka_exporter_tgz }}'
        timeout: '60'
        mode: '0644'

    - name: "Ensure install dir exists"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ kafka_exporter_install_dir }}'
        - '{{ kafka_exporter_temp_dir }}/kafka_exporter'

    - name: "Unarchive kafka_exporter..."
      ansible.builtin.unarchive:
        src: '{{ kafka_exporter_temp_dir }}/{{ kafka_exporter_tgz }}'
        dest: '{{ kafka_exporter_temp_dir }}/kafka_exporter'
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: '0644'

    - name: "Copy kafka_exporter binary..."
      ansible.builtin.copy:
        src: '{{ kafka_exporter_temp_dir }}/kafka_exporter/kafka_exporter'
        dest: '{{ kafka_exporter_install_dir }}/kafka_exporter'
        remote_src: true
        mode: '0755'

    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: '{{ kafka_exporter_temp_dir }}/kafka_exporter'
        state: absent

- name: "Create systemd for kafka_exporter"
  ansible.builtin.template:
    src: 'kafka_exporter.service.j2'
    dest: '/etc/systemd/system/kafka_exporter.service'
    mode: '0640'
  notify: "restart kafka_exporter"

- name: "Start kafka_exporter.service"
  ansible.builtin.service:
    name: kafka_exporter
    state: started
    enabled: true
    daemon_reload: true
