---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Check for kafka_exporter binary"
  stat:
    path: '{{ kafka_exporter_install_dir }}/kafka_exporter'
  changed_when: false
  register: kafka_exporter_install

- when: not kafka_exporter_install.stat.exists or kafka_exporter_force_install|bool
  block:
    - name: "Download kafka_exporter..."
      get_url:
        url: '{{ kafka_exporter_tgz_url }}'
        dest: '{{ kafka_exporter_temp_dir }}/{{ kafka_exporter_tgz }}'
        timeout: '60'
        mode: '0644'

    - name: "Ensure install dir exists"
      file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ kafka_exporter_install_dir }}'
        - '{{ kafka_exporter_temp_dir }}/kafka_exporter'

    - name: "Unarchive kafka_exporter..."
      unarchive:
        src: '{{ kafka_exporter_temp_dir }}/{{ kafka_exporter_tgz }}'
        dest: '{{ kafka_exporter_temp_dir }}/kafka_exporter'
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: '0644'

    - name: "Copy kafka_exporter binary..."
      copy:
        src: '{{ kafka_exporter_temp_dir }}/kafka_exporter/kafka_exporter'
        dest: '{{ kafka_exporter_install_dir }}/kafka_exporter'
        remote_src: true
        mode: '0755'

    - name: "Remove temporary directory"
      file:
        path: '{{ kafka_exporter_temp_dir }}/kafka_exporter'
        state: absent

- name: "Create systemd for kafka_exporter"
  template:
    src: 'kafka_exporter.service.j2'
    dest: '/etc/systemd/system/kafka_exporter.service'
    mode: '0640'
  notify: "restart kafka_exporter"

- name: Start kafka_exporter.service
  systemd:
    name: kafka_exporter
    state: started
    enabled: true
    daemon_reload: true
